### ISSUE TITLE
KeyError: 'cipher'

### ISSUE THREAD

**Issue by Akarsh711** [hbmartin/pytube3#3]
### I am using the latest version and got this error 

```python
 c:\Users\iball\Desktop\yo_downloader>py test.py
Traceback (most recent call last):
  File "C:\Users\iball\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\extract.py", line 297, in apply_descrambler
    for format_item in formats
  File "C:\Users\iball\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\extract.py", line 297, in <listcomp>
    for format_item in formats
KeyError: 'url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    yt = YouTube("https://youtu.be/831ur0X3kfk")
  File "C:\Users\iball\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\__main__.py", line 92, in __init__
    self.descramble()
  File "C:\Users\iball\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\__main__.py", line 132, in descramble
    apply_descrambler(self.player_config_args, fmt)
  File "C:\Users\iball\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\extract.py", line 301, in apply_descrambler
    parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
  File "C:\Users\iball\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\extract.py", line 301, in <listcomp>
    parse_qs(formats[i]["cipher"]
```
test.py :
```python
from pytube import YouTube
yt = YouTube("https://youtu.be/831ur0X3kfk")
```

**Comment by godfrednanaowusu** [comment]
I noticed i get this issue when youtube claims the video has copyright problems, i hope this helps solve the problem.

**Comment by Akarsh711** [comment]
ya but that's not the case with me actually. I tried other downloader for same video and that's work.

**Comment by TermoZour** [comment]
I'm getting that same issue today. Also tried with a link embedded on a website and I can't play it back there either.

**Comment by abbasbeydoun** [comment]
Same issue here with this video

https://www.youtube.com/watch?v=hS5CfP8n_js
