### ISSUE TITLE
Progress callback seems to be broken.

### ISSUE THREAD

**Issue by jslay88** [hbmartin/pytube3#65]
Using 9.6.4

```
Traceback (most recent call last):
  File "C:\Scripts\YouTubeDownload\qt_assets\tabs\downloader.py", line 203, in download_streams
    proxies=self.__download_manager.get_proxies())
  File "C:\Scripts\YouTubeDownload\utils.py", line 72, in download_youtube_video
    stream.download(output_path=output_path, filename=filename)
  File "C:\Scripts\YouTubeDownload\venv\lib\site-packages\pytube\streams.py", line 241, in download
    self.on_progress(chunk, fh, bytes_remaining)
  File "C:\Scripts\YouTubeDownload\venv\lib\site-packages\pytube\streams.py", line 302, in on_progress
    self._monostate.on_progress(self, chunk, bytes_remaining)
TypeError: update_progress_bar() missing 1 required positional argument: 'bytes_remaining'
```

**Comment by Choromanski** [comment]
I'm unable to replicate this issue.
What was the command you were trying to run?

**Comment by hbmartin** [comment]
@jslay88 the on_progress handler interface had a breaking change as part of implementing fast download. I didn't do a great job documenting at the time, updated in : aba400f31fab43c9921d0e1d6bb8045aced80c81
I also made a YTD PR for this change.
